apiVersion: v1
kind: Pod
spec:
  containers:
  - name: cdt
    image: quay.io/eclipse-cdt/cdt-infra-eclipse-full@sha256:2742055ec491d978126159d35286b540c3c183a5fc3ba1010be3cd0bf8106da7
    tty: true
    args: ["/bin/sh", "-c", "/home/vnc/.vnc/xstartup.sh && cat"]
    resources:
      requests:
        memory: "3Gi"
        cpu: "2"
      limits:
        memory: "3Gi"
        cpu: "2"
    volumeMounts:
    - name: settings-xml
      mountPath: /home/jenkins/.m2/settings.xml
      subPath: settings.xml
      readOnly: true
    - name: m2-repo
      mountPath: /home/jenkins/.m2/repository
  volumes:
  - name: settings-xml
    secret:
      secretName: m2-secret-dir
      items:
      - key: settings.xml
        path: settings.xml
  - name: m2-repo
    emptyDir: {}
