apiVersion: v1
kind: Pod
spec:
  containers:
  - name: cdt
    image: quay.io/eclipse-cdt/cdt-infra-eclipse-full@sha256:24cf645c332d44f301c22747434b3aa8c3c0aad58c6f7d83803a55e6cf56eee0
    tty: true
    args: ["/bin/sh", "-c", "/home/vnc/.vnc/xstartup.sh && cat"]
    resources:
      requests:
        memory: "2662Mi"
        cpu: "1"
      limits:
        memory: "2662Mi"
        cpu: "1"
    volumeMounts:
    - name: settings-xml
      mountPath: /home/jenkins/.m2/settings.xml
      subPath: settings.xml
      readOnly: true
    - name: m2-repo
      mountPath: /home/jenkins/.m2/repository
  volumes:
  - name: settings-xml
    secret:
      secretName: m2-secret-dir
      items:
      - key: settings.xml
        path: settings.xml
  - name: m2-repo
    emptyDir: {}
